require('core.lsp')

require('config.options')
require('config.keymaps')

require('plugins.theme')
require('plugins.conform')
require('plugins.blink')
require('plugins.oil')
require('plugins.mason')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.misc')
require('plugins.lazygit')
require('plugins.lualine')
require('plugins.bufferline')
